image: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "12.4.0"
      ELECTRON: "6.0.9"

matrix:
  fast_finish: true

platform:
  - x64

configuration:
  - Release

install:
  - ps: |
      Install-Product node $env:nodejs_version x64
      if ($env:ELECTRON) {
        $env:npm_config_target=$env:ELECTRON
        $env:npm_config_disturl="https://atom.io/download/electron"
        $env:npm_config_runtime="electron"
        $env:npm_config_build_from_source="true"
      }
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\ctags
      npm install
      npm run build
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\fuzzy-native
      npm install
      npm run build
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\keytar
      npm install
      npm run build
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\pty
      npm install
      npm run tsc
      npm run build

test_script:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\ctags
      IF NOT DEFINED ELECTRON (npm test)
      node_modules/.bin/node-pre-gyp package testpackage
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\fuzzy-native
      IF NOT DEFINED ELECTRON (npm test)
      node_modules/.bin/node-pre-gyp package testpackage
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\keytar
      IF NOT DEFINED ELECTRON (npm test)
      node_modules/.bin/node-pre-gyp package testpackage
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\pty
      IF NOT DEFINED ELECTRON (npm test)
      node_modules/.bin/node-pre-gyp package testpackage

build: off

artifacts:
  - path: '**\build\stage\*.tar.gz'

deploy:
  description: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: rdBc+YLCOY3cFD38CjEn4Z/b6uvCBFiwHAiLg5Lwzs2WoPS0uLTgrW2puQSV5oZp
  artifact: /.*\.tar\.gz/
  force_update: true
  on:
    appveyor_repo_tag: true
